// src/dictionaries/fr/appointments.fr.ts
export const appointments = {
  title: "Rendez-vous",
  subtitle: "Tous les rendez-vous pris via votre assistant.",
  newBtn: "Nouveau RDV",
  errorLoad: "Erreur lors du chargement.",
  createSuccess: "RDV créé !",
  deleteSuccess: "RDV supprimé.",
  deleteError: "Erreur suppression.",
  confirmDelete: "Supprimer ce rendez-vous ?",
  noData: "Aucun rendez-vous pour cette période.",
  statuses: {
    pending: "En attente",
    confirmed: "Confirmé",
    done: "Terminé",
    cancelled: "Annulé",
  },
  channels: { whatsapp: "WhatsApp", voice: "Vocal", manual: "Manuel" },
  table: {
    client: "Client",
    service: "Service",
    date: "Date & Heure",
    channel: "Canal",
    status: "Statut",
  },
  viewWeek: "Semaine",
  viewDay: "Jour",
  today: "Aujourd'hui",
  prevWeek: "Semaine précédente",
  nextWeek: "Semaine suivante",
  prevDay: "Jour précédent",
  nextDay: "Jour suivant",
  noSlots: "Aucun RDV ce jour.",
  slotFree: "Créneau libre",
  configTitle: "Configuration des créneaux",
  configSubtitle:
    "Le bot utilise ces paramètres pour proposer des horaires disponibles.",
  durationLabel: "Durée d'un RDV",
  durationUnit: "min",
  bufferLabel: "Tampon entre 2 RDV",
  bufferUnit: "min",
  configSaved: "Configuration enregistrée.",
  detailTitle: "Détail du rendez-vous",
  detailClient: "Client",
  detailPhone: "Téléphone",
  detailService: "Service",
  detailDate: "Date & heure",
  detailChannel: "Canal",
  detailNotes: "Notes",
  detailStatus: "Statut",
  modal: {
    createTitle: "Nouveau RDV",
    editTitle: "Modifier le RDV",
    btnCreate: "Créer",
    btnUpdate: "Mettre à jour",
    fields: {
      service: "Service",
      clientName: "Nom du client",
      clientPhone: "Téléphone",
      clientEmail: "Email (optionnel)",
      scheduledAt: "Date et heure",
      status: "Statut",
      notes: "Notes",
    },
  },
} as const;
