// src/dictionaries/en/bots.en.ts
export const bots = {
  title: "My Bots",
  subtitle: "Manage your virtual assistants.",
  newBtn: "New bot",
  errorLoad: "Error loading bots.",
  createSuccess: "Bot created successfully!",
  deleteSuccess: "Bot deleted.",
  deleteError: "Error deleting bot.",
  confirmDelete: "Permanently delete this bot?",
  noData: "No bots configured.",
  statusActive: "Active",
  statusPaused: "Paused",
  statusArchived: "Archived",
  providerWaha: "WAHA",
  providerMeta: "Meta API",
  providerGemini: "Gemini",
  providerOpenAI: "OpenAI",
  publish: "Publish bot",
  unpublish: "Unpublish",
  publishConfirm: "Publish this bot? Customers will be able to access it.",
  unpublishConfirm: "Unpublish this bot? Customers will no longer have access.",
  publishSuccess: "Bot published successfully!",
  unpublishSuccess: "Bot unpublished.",
  publishError: "Error publishing bot.",
  settingsTab: "Settings",
  settingsSave: "Save",
  settingsSaved: "Settings saved!",
  detailTab: "Detail",
  conversationsTab: "Conversations",
  agendaTab: "Agenda",
  statsTab: "Statistics",
  whatsappTab: "WhatsApp",
  testBtn: "Test bot",
  testTitle: "Test bot",
  testSubtitle: "Simulate a conversation with your assistant.",
  testBackDashboard: "Back to dashboard",
  testWhatsappPlaceholder: "Write a message…",
  testVoiceTitle: "Voice Assistant",
  testVoiceSubtitle: "Press to simulate a call",
  testVoiceCallBtn: "Simulate a call",
  testVoiceEndBtn: "Hang up",
  testVoiceCalling: "Call in progress…",
  testVoiceConnected: "Connected",
  testTyping: "Assistant is replying…",
  testPublishedBadge: "Online",
  testUnpublishedBadge: "Offline",
  testSessions: "Test sessions",
  testSessionsEmpty: "No test sessions yet.",
  testNewSession: "New session",
  testCollectedData: "Collected data",
  testIntentions: "Detected intentions",
  testTokensUsed: "Tokens used",
  testActionsExecuted: "Actions executed",
  testConfigTitle: "AI Configuration",
  testConfigPrompt: "System prompt",
  testConfigTemperature: "Temperature",
  testConfigMaxTokens: "Max tokens",
  testConfigSave: "Save config",
  testConfigSaved: "Configuration saved!",
  testConfigError: "Error saving configuration.",
  testSendError: "Error sending message.",
  testSummaryTitle: "Client profile",
  testEmailsSent: "Email(s) sent",
  testHandoffAlert: "Human handoff triggered",
  testResetSession: "Reset session",
  statsMessages: "Messages handled",
  statsCalls: "Calls handled",
  statsAppointments: "Appointments scheduled",
  statsConversations: "Conversations",
  conversationsEmpty: "No conversations for this bot.",
  conversationChannel: "Channel",
  conversationDate: "Date",
  conversationMessages: "messages",
  reportTitle: "Conversation report",
  reportSummary: "Summary",
  reportTakeaways: "Key points",
  reportActions: "Actions taken",
  reportContact: "Customer details",
  reportServices: "Services discussed",
  reportAppointment: "Appointment scheduled",
  reportHandoff: "Human handoff",
  reportHandoffReason: "Reason for handoff",
  reportNoAppointment: "No appointment scheduled",
  reportNoHandoff: "No handoff",
  actionTypes: {
    appointment: "Appointment scheduled",
    handoff: "Human handoff",
    faq: "FAQ answered",
    service_info: "Service info",
    contact_collected: "Contact collected",
  },
  filters: { searchPlaceholder: "Search a bot…", allStatuses: "All" },
  table: {
    name: "Name",
    whatsapp: "WhatsApp",
    voice: "Voice AI",
    status: "Status",
    date: "Created",
  },
  modal: {
    createTitle: "New Bot",
    editTitle: "Edit Bot",
    btnCreate: "Create bot",
    btnUpdate: "Update",
    fields: {
      name: "Bot name",
      welcome: "Welcome message",
      personality: "Personality",
      languages: "Languages",
      whatsappProvider: "WhatsApp provider",
      voiceProvider: "Voice AI provider",
      isActive: "Activate immediately",
    },
  },
  whatsapp: {
    panelTitle: "WhatsApp Connection",
    panelSubtitle: "Link this bot to your WhatsApp account",
    statusStopped: "Disconnected",
    statusStarting: "Starting…",
    statusScanQR: "Waiting for scan",
    statusWorking: "Connected",
    statusFailed: "Failed",
    descriptionStopped:
      "Link your WhatsApp number to this bot so it automatically receives and replies to incoming messages.",
    connectButton: "Connect WhatsApp",
    disconnectButton: "Disconnect",
    retryButton: "Retry",
    disconnectConfirmTitle: "Disconnect WhatsApp?",
    disconnectConfirmBody:
      "The bot will no longer receive WhatsApp messages until reconnected.",
    disconnectConfirmButton: "Yes, disconnect",
    disconnectSuccess: "WhatsApp bot disconnected.",
    notPublishedTitle: "Bot not published",
    notPublishedMessage:
      "You must first publish this bot before linking it to a WhatsApp account.",
    errorBotNotPublished:
      "This bot must be published before connecting it to WhatsApp.",
    startingMessage: "Starting connection… please wait.",
    qrGenerating: "Generating QR code…",
    qrAlt: "WhatsApp QR code to scan",
    qrInstructionsTitle: "How to scan the QR code",
    qrStep1: "Open WhatsApp on your phone",
    qrStep2: "Go to Settings → Linked devices",
    qrStep3: "Tap 'Link a device' and scan this QR code",
    qrExpireHint:
      "The QR code expires after ~20 seconds. It refreshes automatically.",
    phoneLabel: "Connected number",
    connectedAtLabel: "Connected on",
    workingNote:
      "This bot now automatically receives WhatsApp messages and replies using its AI. All exchanges are recorded in the Conversations tab.",
    infoLabel: "Info:",
    singleSessionInfo:
      "Only one WhatsApp bot can be connected at a time on the platform.",
  },
} as const;
