// src/dictionaries/en/dashboard.en.ts
export const dashboard = {
  pme: {
    title: "Dashboard",
    welcome: "Hello",
    subtitle: "Here is your virtual assistant activity.",
    messagesToday: "Messages today",
    callsToday: "Calls today",
    appointmentsToday: "Appointments today",
    activeConversations: "Active conversations",
    thisWeek: "This week",
    recentConversations: "Recent conversations",
    noConversations: "No recent conversations.",
    channel_whatsapp: "WhatsApp",
    channel_voice: "Voice",
    quickLinks: "Quick access",
    subscription: "My subscription",
    usageMessages: "Messages used",
    usageCalls: "Calls used",
    todayAppointments: "Today's appointments",
    noAppointmentsToday: "No appointments today.",
    viewAgenda: "View agenda →",
    emailStats: "Reminder emails",
    emailsSentWeek: "sent this week",
    emailsOpened: "opened",
    emailsFailed: "failed",
    conversationDetail: "Conversation detail",
    conversationHistory: "History",
    conversationAction: "Action triggered",
    conversationNoAction: "No action",
    noSubscription: "No active subscription.",
  },
} as const;
