// src/dictionaries/fr/dashboard.fr.ts
export const dashboard = {
  pme: {
    title: "Tableau de bord",
    welcome: "Bonjour",
    subtitle: "Voici l'activité de votre assistant virtuel.",
    messagesToday: "Messages aujourd'hui",
    callsToday: "Appels aujourd'hui",
    appointmentsToday: "RDV aujourd'hui",
    activeConversations: "Conversations actives",
    thisWeek: "Cette semaine",
    recentConversations: "Dernières conversations",
    noConversations: "Aucune conversation récente.",
    channel_whatsapp: "WhatsApp",
    channel_voice: "Vocal",
    quickLinks: "Accès rapides",
    subscription: "Mon abonnement",
    usageMessages: "Messages utilisés",
    usageCalls: "Appels utilisés",
    todayAppointments: "RDV aujourd'hui",
    noAppointmentsToday: "Aucun RDV aujourd'hui.",
    viewAgenda: "Voir l'agenda →",
    emailStats: "Emails de rappel",
    emailsSentWeek: "envoyés cette semaine",
    emailsOpened: "ouverts",
    emailsFailed: "échoués",
    conversationDetail: "Détail conversation",
    conversationHistory: "Historique",
    conversationAction: "Action déclenchée",
    conversationNoAction: "Aucune action",
    noSubscription: "Aucun abonnement actif.",
  },
} as const;
