// src/dictionaries/en/knowledge.en.ts
export const knowledge = {
  title: "Knowledge base",
  subtitle: "Everything your assistant needs to know about your business.",
  tabGeneral: "General info",
  tabLocations: "Branches",
  tabFaq: "FAQ",
  tabServices: "Services & Pricing",
  botSection: "Virtual assistant & Branding",
  welcomeMessage: "Welcome message",
  botTone: "Communication tone",
  toneFormal: "Formal",
  toneSemiFormal: "Semi-formal",
  toneCasual: "Casual",
  toneInherit: "Inherit from general",
  botPersonality: "Bot personality",
  botLanguages: "Bot languages",
  botSignature: "Auto signature",
  slogan: "Company slogan",
  contactSection: "Main contacts",
  contactWhatsapp: "WhatsApp",
  contactPhone: "Phone",
  contactEmail: "Email",
  website: "Website",
  transferSection: "Transfer to a human",
  transferSubtitle:
    "When the bot cannot respond, it transfers to these contacts.",
  transferWhatsapp: "Transfer WhatsApp",
  transferPhone: "Transfer phone",
  transferEmail: "Transfer email",
  transferMessage: "Transfer message",
  extraInfo: "Additional information",
  hoursOpening: "Opening hours",
  hoursAppointments: "Appointment hours",
  saveSuccess: "Saved successfully.",
  addLocation: "Add a branch",
  editLocation: "Edit branch",
  locationName: "Branch name",
  locationAddress: "Address",
  locationDeleted: "Branch deleted.",
  locationDeleteConfirm: "Delete this branch?",
  noLocations: "No branches configured.",
  faqCount: "questions configured",
  manageFaq: "Manage FAQ",
  manageServices: "Manage services",
  serviceWelcomeMessage: "Specific welcome message",
  serviceBotDescription: "Description for the bot",
  serviceConditions: "Conditions & prerequisites",
  serviceConfirmationMessage: "Appointment confirmation message",
  knowledgeSection: "Assistant configuration",
  locationServicesLabel: "Services offered at this branch",
  noServicesCreated: "No services created.",
  newService: "New service",
  editService: "Edit service",
  deleteService: "Delete this service?",
  serviceDeleted: "Service deleted.",
  serviceCreated: "Service created!",
  serviceUpdated: "Service updated.",
  serviceName: "Service name",
  servicePrice: "Price (XAF)",
  serviceDuration: "Duration (minutes)",
  serviceDescription: "Description",
  serviceActive: "Service active",
} as const;
