// src/dictionaries/fr/knowledge.fr.ts
export const knowledge = {
  title: "Base de connaissance",
  subtitle: "Tout ce que votre assistant doit savoir sur votre entreprise.",
  tabGeneral: "Infos générales",
  tabLocations: "Agences",
  tabFaq: "FAQ",
  tabServices: "Services & Tarifs",
  botSection: "Assistant virtuel & Branding",
  welcomeMessage: "Message d'accueil",
  botTone: "Ton de communication",
  toneFormal: "Formel",
  toneSemiFormal: "Semi-formel",
  toneCasual: "Décontracté",
  toneInherit: "Hériter du général",
  botPersonality: "Personnalité du bot",
  botLanguages: "Langues du bot",
  botSignature: "Signature automatique",
  slogan: "Slogan de l'entreprise",
  contactSection: "Contacts principaux",
  contactWhatsapp: "WhatsApp",
  contactPhone: "Téléphone",
  contactEmail: "Email",
  website: "Site web",
  transferSection: "Transfert vers un humain",
  transferSubtitle:
    "Quand le bot ne peut pas répondre, il transfère vers ces contacts.",
  transferWhatsapp: "WhatsApp de transfert",
  transferPhone: "Téléphone de transfert",
  transferEmail: "Email de transfert",
  transferMessage: "Message de transfert",
  extraInfo: "Informations supplémentaires",
  hoursOpening: "Horaires d'ouverture",
  hoursAppointments: "Horaires de réception RDV",
  saveSuccess: "Enregistré avec succès.",
  addLocation: "Ajouter une agence",
  editLocation: "Modifier l'agence",
  locationName: "Nom de l'agence",
  locationAddress: "Adresse",
  locationDeleted: "Agence supprimée.",
  locationDeleteConfirm: "Supprimer cette agence ?",
  noLocations: "Aucune agence configurée.",
  faqCount: "questions configurées",
  manageFaq: "Gérer la FAQ",
  manageServices: "Gérer les services",
  serviceWelcomeMessage: "Message d'accueil spécifique",
  serviceBotDescription: "Description pour le bot",
  serviceConditions: "Conditions & prérequis",
  serviceConfirmationMessage: "Message de confirmation RDV",
  knowledgeSection: "Configuration assistant",
  locationServicesLabel: "Services proposés dans cette agence",
  noServicesCreated: "Aucun service créé.",
  newService: "Nouveau service",
  editService: "Modifier le service",
  deleteService: "Supprimer ce service ?",
  serviceDeleted: "Service supprimé.",
  serviceCreated: "Service créé !",
  serviceUpdated: "Service mis à jour.",
  serviceName: "Nom du service",
  servicePrice: "Prix (XAF)",
  serviceDuration: "Durée (minutes)",
  serviceDescription: "Description",
  serviceActive: "Service actif",
} as const;
