// src/dictionaries/fr/nav.fr.ts
export const nav = {
  dashboard: "Tableau de bord",
  bots: "Mes Bots",
  services: "Services",
  appointments: "Rendez-vous",
  billing: "Facturation",
  profile: "Mon Profil",
  faq: "FAQ",
  providers: "Fournisseurs",
  subscriptions: "Abonnements",
  restartOnboarding: "Relancer l'assistant",
  quickSetup: "Configuration rapide",
  help: "Demander de l'aide",
  tutorial: "Tutoriel interface",
  knowledge: "Base de connaissance",
  feedback: "Laisser un témoignage",
  bug: "Signaler un problème",
  conversations: "Conversations",
  contacts: "Contacts",
  settings: "Paramètres",
} as const;
