// src/dictionaries/en/onboarding.en.ts
export const onboarding = {
  accountTitle: "Create your account",
  accountSubtitle: "Launch your virtual assistant in minutes.",
  stepLabels: ["Your business", "Your plan", "Payment", "Confirmation"] as const,
  welcomeGiftTitle: "Welcome gift",
  welcomeGiftDesc: "Your wallet has been credited with 10,000 XAF!",
  welcomeGiftSub: "Use it to activate your first subscription.",
  profileTitle: "Tell us about your business",
  profileSubtitle:
    "This information helps your assistant respond better to your customers.",
  emailCheckTitle: "Check your email",
  emailCheckSubtitle: "A confirmation link was sent to",
  emailCheckWaiting: "Verifying…",
  accountExistsActive: "Account already active. Please sign in.",
  googleBtn: "Continue with Google",
  orContinueWith: "Or continue with",
  planTitle: "Choose your subscription",
  planSubtitle: "You can change your plan at any time from your account.",
  paymentTitle: "Finalize your subscription",
  paymentSubtitle: "Your current balance:",
  paymentWalletBtn: "Pay with my wallet",
  paymentRechargeBtn: "Top up then pay",
  paymentInsufficient: "Insufficient balance for this plan.",
  paymentSuccess: "Payment successful!",
  successTitle: "Your assistant is ready!",
  successSubtitle: "Your Bot Pack has been activated. Welcome to AGT Platform.",
  successBtn: "Go to my dashboard",
  selectedPlan: "Selected plan",
  walletBalance: "Wallet balance",
  toPay: "Amount due",
  restartBtn: "Restart setup assistant",
  fields: {
    companyName: "Company name",
    sector: "Business sector",
    description: "Description (what you do)",
    whatsapp: "Professional WhatsApp number",
    phone: "Phone",
    email: "Email address",
    password: "Password",
    confirmPassword: "Confirm password",
    fullName: "Your full name",
  },
  sectors: {
    sante: "Healthcare",
    juridique: "Legal",
    beaute: "Beauty & Wellness",
    restauration: "Food & Restaurant",
    commerce: "Commerce & Distribution",
    education: "Education & Training",
    immobilier: "Real Estate",
    transport: "Transport & Logistics",
    finance: "Finance & Insurance",
    autre: "Other",
  },
} as const;
